version: "3"
services:
  db:
    image: postgres:12
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - -h
        - localhost
        - -u
        - ${DB_USER}
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - postgres:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 1234:8080
volumes:
  mysql: ~
  postgres: ~
