/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GrpcMethod } from "@nestjs/microservices";
import { SearchResultService } from "../searchResult.service";
import { SearchResultCreateInput } from "./SearchResultCreateInput";
import { SearchResultWhereInput } from "./SearchResultWhereInput";
import { SearchResultWhereUniqueInput } from "./SearchResultWhereUniqueInput";
import { SearchResultFindManyArgs } from "./SearchResultFindManyArgs";
import { SearchResultUpdateInput } from "./SearchResultUpdateInput";
import { SearchResult } from "./SearchResult";

export class SearchResultGrpcControllerBase {
  constructor(protected readonly service: SearchResultService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SearchResult })
  @GrpcMethod("SearchResultService", "createSearchResult")
  async createSearchResult(
    @common.Body() data: SearchResultCreateInput
  ): Promise<SearchResult> {
    return await this.service.createSearchResult({
      data: data,
      select: {
        associatedKeyword: true,
        createdAt: true,
        id: true,
        resultContent: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [SearchResult] })
  @ApiNestedQuery(SearchResultFindManyArgs)
  @GrpcMethod("SearchResultService", "searchResults")
  async searchResults(@common.Req() request: Request): Promise<SearchResult[]> {
    const args = plainToClass(SearchResultFindManyArgs, request.query);
    return this.service.searchResults({
      ...args,
      select: {
        associatedKeyword: true,
        createdAt: true,
        id: true,
        resultContent: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SearchResult })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("SearchResultService", "searchResult")
  async searchResult(
    @common.Param() params: SearchResultWhereUniqueInput
  ): Promise<SearchResult | null> {
    const result = await this.service.searchResult({
      where: params,
      select: {
        associatedKeyword: true,
        createdAt: true,
        id: true,
        resultContent: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SearchResult })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("SearchResultService", "updateSearchResult")
  async updateSearchResult(
    @common.Param() params: SearchResultWhereUniqueInput,
    @common.Body() data: SearchResultUpdateInput
  ): Promise<SearchResult | null> {
    try {
      return await this.service.updateSearchResult({
        where: params,
        data: data,
        select: {
          associatedKeyword: true,
          createdAt: true,
          id: true,
          resultContent: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SearchResult })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("SearchResultService", "deleteSearchResult")
  async deleteSearchResult(
    @common.Param() params: SearchResultWhereUniqueInput
  ): Promise<SearchResult | null> {
    try {
      return await this.service.deleteSearchResult({
        where: params,
        select: {
          associatedKeyword: true,
          createdAt: true,
          id: true,
          resultContent: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
